name: auto-update-cron
on:
  schedule:
    - cron: '0 0 * * *'
jobs:
  build:
    name: Trigger Site Rebuild
    runs-on: ubuntu-latest
    steps:
      - name: Call Vercel Hook
        run: curl -X POST "https://api.vercel.com/v1/integrations/deploy/prj_hVaaikqE7jbMKBTvx2xnVMaOv4sr/Ub1YJtZ0fn?buildCache=false"